---
    name: Build and deploy .NET Core app to Azure
    on:
        push:
            branches:
                - main
    jobs:
        build:
            runs-on: ubuntu-latest
        
            steps:
            - uses: actions/checkout@v2
        
            